name: Code generation

on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate sdRDM library
      uses: JR-1991/generate-sdrdm-api@v3
      with:
        library_name: "PorousPy"
        schema_path: "./specifications/model.md"
        schema: "true"
        branch: "main"
